testtrigger:
    trigger:
        include:
            - project: 'devops/deployment'
              ref: 'template'
              file: '.gitlab-ci-backend.yml'
    only:
        - test

prodtrigger:
    trigger:
        include:
            - project: 'devops/deployment'
              ref: 'template'
              file: '.gitlab-ci-backend.yml'
    only:
        - main
